# Site settings
title: SunOddman
subtitle: æ¿€æ‰¬é’æ˜¥ï¼Œæ¢¦æƒ³èµ·èˆª
email: liuzexiang@live.cn
description: äººç”Ÿå°±åƒä¸€åœºæ—…è¡Œ<br />ä¸å¿…åœ¨ä¹ç»ˆç‚¹<br />åœ¨ä¹çš„<br />åªæ˜¯æ²¿é€”çš„é£æ™¯
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: SunÂ·Oddman
street_address: Chang Ping
city: Beijing
state: 
zip_code: 
country: the People's Republic of China
phone: èµèµ5å…ƒä»¥ä¸Šå¯è§ğŸ‘»

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/SunOddman
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/107196077456137636170
instagram_url: 
linkedin_url: https://www.linkedin.com/in/æ³½ç¥¥-åˆ˜-520414107/
pinterest_url:
slack_url:
twitter_url: 
weibo_url: 

# Build settings
markdown: kramdown

sass:
  style: compressed
